import 'package:express3/core/models/wilaya.dart';

List<wilaya> LWS=[
  wilaya(16,'Alger','Alger',i1: 650, i2: 400,['Bab Ezzouar','Mohammadia'],
      {
        'Bab Ezzouar': 'AADL, Les bananiers',
        'Mohammadia': 'Mohammadia',
      },
      [
        "Ain Benian",
        "Ain Taya",
        "Alger Centre",
        "Bab El Oued",
        "Bab Ezzouar",
        "Baba Hesen",
        "Bachedjerah",
        "Bains Romains",
        "Baraki",
        "Ben Aknoun",
        "Beni Messous",
        "Bir Mourad Rais",
        "Bir Touta",
        "Birkhadem",
        "Bologhine Ibnou Ziri",
        "Bordj El Bahri",
        "Bordj El Kiffan",
        "Bourouba",
        "Bouzareah",
        "Casbah",
        "Cheraga",
        "Dar El Beida",
        "Dely Ibrahim",
        "Djasr Kasentina",
        "Douira",
        "Draria",
        "El Achour",
        "El Biar",
        "El Harrach",
        "El Madania",
        "El Magharia",
        "El Merssa",
        "El Mouradia",
        "Herraoua",
        "Hussein Dey",
        "Hydra",
        "Kheraisia",
        "Kouba",
        "Les Eucalyptus",
        "Maalma",
        "Mohamed Belouzdad",
        "Mohammadia",
        "Oued Koriche",
        "Oued Smar",
        "Ouled Chebel",
        "Ouled Fayet",
        "Rahmania",
        "Rais Hamidou",
        "Reghaia",
        "Rouiba",
        "Sehaoula",
        "Setaouali",
        "Sidi M'hamed",
        "Sidi Moussa",
        "Souidania",
        "Tessala El Merdja",
        "Zeralda"
      ]
  ),
  wilaya(42,'Tipaza','Tipaza',i1: 700, i2: 400,['Tipaza'],
      {
            'Tipaza': 'Cité AADL 1700 logts le jardine',
      },
      [
        "Aghbal",
        "Ahmer El Ain",
        "Ain Tagourait",
        "Attatba",
        "Beni Mileuk",
        "Bou Haroun",
        "Bou Ismail",
        "Bourkika",
        "Chaiba",
        "Cherchell",
        "Damous",
        "Douaouda",
        "Fouka",
        "Gouraya",
        "Hadjout",
        "Hadjret Ennous",
        "Khemisti",
        "Kolea",
        "Larhat",
        "Menaceur",
        "Merad",
        "Messelmoun",
        "Nador",
        "Sidi Amar",
        "Sidi Ghiles",
        "Sidi Rached",
        "Sidi Semiane",
        "Tipaza"
      ]
  ),
  wilaya(9,'Blida','Blida',i1: 700, i2: 400,['Blida'],
      {
            'Blida': '13 Mai en face Banque BNA boulevard Top chop',
      },
      [
        "Ain Romana",
        "Beni Mered",
        "Beni Tamou",
        "Benkhelil",
        "Blida",
        "Bouarfa",
        "Boufarik",
        "Bougara",
        "Bouinan",
        "Chebli",
        "Chiffa",
        "Chrea",
        "Djebabra",
        "El Affroun",
        "Guerrouaou",
        "Hammam Melouane",
        "Larbaa",
        "Meftah",
        "Mouzaia",
        "Oued Djer",
        "Oued El Alleug",
        "Ouled Slama",
        "Ouled Yaich",
        "Souhane",
        "Souma"
      ]
  ),
  wilaya(27,'Mostaganem','Mostaganem',i1: 700, i2: 450,['Mostaganem'],
      {
            'Mostaganem': 'Rue Belarbi M Barek',
      },
      [
        "Achaacha",
        "Ain Boudinar",
        "Ain Nouissy",
        "Ain Sidi Cherif",
        "Ain Tedles",
        "Benabdelmalek Ramdane",
        "Bouguirat",
        "Fornaka",
        "Hadjadj",
        "Hassi Mameche",
        "Hassiane",
        "Khadra",
        "Kheir Eddine",
        "Mansourah",
        "Mazagran",
        "Mesra",
        "Mostaganem",
        "Nekmaria",
        "Oued El Kheir",
        "Ouled Boughalem",
        "Ouled Maalah",
        "Safsaf",
        "Sayada",
        "Sidi Ali",
        "Sidi Belaattar",
        "Sidi Lakhdar",
        "Sirat",
        "Souaflia",
        "Sour",
        "Stidia",
        "Tazgait",
        "Touahria"
      ]
  ),
  wilaya(26,'Médéa','Medea',i1: 700, i2: 400,['Medea'],
      {
            'Medea': 'Pôle urbain',
      },
      [
        "Ain Boucif",
        "Ain Ouksir",
        "Aissaouia",
        "Aziz",
        "Baata",
        "Ben Chicao",
        "Beni Slimane",
        "Berrouaghia",
        "Bir Ben Laabed",
        "Boghar",
        "Bouaiche",
        "Bouaichoune",
        "Bouchrahil",
        "Boughzoul",
        "Bouskene",
        "Chabounia",
        "Chelalet El Adhaoura",
        "Cheniguel",
        "Damiat",
        "Derrag",
        "Deux Bassins",
        "Djouab",
        "Draa Essamar",
        "El Azizia",
        "El Guelbelkebir",
        "El Hamdania",
        "El Omaria",
        "El Ouinet",
        "Hannacha",
        "Kef Lakhdar",
        "Khams Djouamaa",
        "Ksar El Boukhari",
        "Maghraoua",
        "Medea",
        "Medjebar",
        "Meftaha",
        "Mezerana",
        "Mihoub",
        "Ouamri",
        "Oued Harbil",
        "Ouled Antar",
        "Ouled Bouachra",
        "Ouled Brahim",
        "Ouled Deid",
        "Ouled Hellal",
        "Ouled Maaref",
        "Oum El Djellil",
        "Ouzera",
        "Rebaia",
        "Saneg",
        "Sedraya",
        "Seghouane",
        "Si Mahdjoub",
        "Sidi Demed",
        "Sidi Naamane",
        "Sidi Rabie",
        "Sidi Zahar",
        "Sidi Ziane",
        "Souagui",
        "Tablat",
        "Tafraout",
        "Tamesguida",
        "Tletat Ed Douair",
        "Zoubiria"
      ]
  ),
  wilaya(14,'Tiaret','Tiaret',i1: 750, i2: 450,['Tiaret'],
      {
            'Tiaret': 'Rue commandant Mejdoub',
      },
      [
        "Ain Bouchekif",
        "Ain Deheb",
        "Ain El Hadid",
        "Ain Kermes",
        "Ain Zarit",
        "Bougara",
        "Chehaima",
        "Dahmouni",
        "Djebilet Rosfa",
        "Djillali Ben Amar",
        "Faidja",
        "Frenda",
        "Guertoufa",
        "Hamadia",
        "Ksar Chellala",
        "Madna",
        "Mahdia",
        "Mechraa Safa",
        "Medrissa",
        "Medroussa",
        "Meghila",
        "Mellakou",
        "Nadorah",
        "Naima",
        "Oued Lilli",
        "Rahouia",
        "Rechaiga",
        "Sebaine",
        "Sebt",
        "Serghine",
        "Si Abdelghani",
        "Sidi Abderrahmane",
        "Sidi Ali Mellal",
        "Sidi Bakhti",
        "Sidi Hosni",
        "Sougueur",
        "Tagdemt",
        "Takhemaret",
        "Tiaret",
        "Tidda",
        "Tousnina",
        "Zmalet El Emir Abdelkade"
      ]
  ),
  wilaya(31,'Oran','Oran',i1: 750, i2: 450,['Bir El Djir'],
      {
            'Bir El Djir': 'Rue colonel Atman hai khmisti',
      },
      [
        "Ain Biya",
        "Ain Kerma",
        "Ain Turk",
        "Arzew",
        "Ben Freha",
        "Bethioua",
        "Bir El Djir",
        "Boufatis",
        "Bousfer",
        "Boutlelis",
        "El Ancar",
        "El Braya",
        "El Kerma",
        "Es Senia",
        "Gdyel",
        "Hassi Ben Okba",
        "Hassi Bounif",
        "Hassi Mefsoukh",
        "Marsat El Hadjadj",
        "Mers El Kebir",
        "Messerghin",
        "Oran",
        "Oued Tlelat",
        "Sidi Ben Yebka",
        "Sidi Chami",
        "Tafraoui"
      ]
  ),
  wilaya(22,'Sidi Bel Abbès','Sidi Bel Abbes',i1: 750, i2: 450,['Sidi Bel Abbes'],
      {
            'Sidi Bel Abbes': 'CITÉ sidi jileli avenue azzouz mohamed 28 logement numéro 11',
      },
      [
            "Ain Adden",
            "Ain El Berd",
            "Ain Kada",
            "Ain Thrid",
            "Ain Tindamine",
            "Amarnas",
            "Badredine El Mokrani",
            "Belarbi",
            "Ben Badis",
            "Benachiba Chelia",
            "Bir El Hammam",
            "Boudjebaa El Bordj",
            "Boukhanafis",
            "Chetouane Belaila",
            "Dhaya",
            "El Hacaiba",
            "Hassi Dahou",
            "Hassi Zahana",
            "Lamtar",
            "M'cid",
            "Makedra",
            "Marhoum",
            "Merine",
            "Mezaourou",
            "Mostefa Ben Brahim",
            "Moulay Slissen",
            "Oued Sebaa",
            "Oued Sefioun",
            "Oued Taourira",
            "Ras El Ma",
            "Redjem Demouche",
            "Sehala Thaoura",
            "Sfissef",
            "Sidi Ali Benyoub",
            "Sidi Ali Boussidi",
            "Sidi Bel Abbes",
            "Sidi Brahim",
            "Sidi Chaib",
            "Sidi Dahou Zairs",
            "Sidi Hamadouche",
            "Sidi Khaled",
            "Sidi Lahcene",
            "Sidi Yacoub",
            "Tabia",
            "Tafissour",
            "Taoudmout",
            "Teghalimet",
            "Telagh",
            "Tenira",
            "Tessala",
            "Tilmouni",
            "Zerouala"
      ]  ),
  wilaya(15,'Tizi Ouzou','Tizi Ouzou',i1: 700, i2: 450,['Boghni','Tizi Ouzou'],
      {
            'Boghni': 'Local N°01 a côté salle des fêtes ben akli, la rocade',
            'Tizi Ouzou': 'Rue frère beggaze n ville a côté dylia market',
      },
      [
        "Abi Youcef",
        "Aghribs",
        "Agouni Gueghrane",
        "Ain El Hammam",
        "Ain Zaouia",
        "Ait Aggouacha",
        "Ait Bouaddou",
        "Ait Boumehdi",
        "Ait Chafaa",
        "Ait Khellili",
        "Ait Mahmoud",
        "Ait Oumalou",
        "Ait Toudert",
        "Ait Yahia",
        "Ait Yahia Moussa",
        "Akbil",
        "Akerrou",
        "Assi Youcef",
        "Azazga",
        "Azeffoun",
        "Beni Aissi",
        "Beni Douala",
        "Beni Yenni",
        "Beni Zikki",
        "Beni Zmenzer",
        "Boghni",
        "Boudjima",
        "Bounouh",
        "Bouzeguene",
        "Djebel Aissa Mimoun",
        "Draa Ben Khedda",
        "Draa El Mizan",
        "Freha",
        "Frikat",
        "Iboudrarene",
        "Idjeur",
        "Iferhounene",
        "Ifigha",
        "Iflissen",
        "Illilten",
        "Illoula Oumalou",
        "Imsouhal",
        "Irdjen",
        "Larba Nath Irathen",
        "Larbaa Nath Irathen",
        "M'kira",
        "Maatkas",
        "Makouda",
        "Mechtras",
        "Mekla",
        "Mizrana",
        "Ouacif",
        "Ouadhias",
        "Ouaguenoune",
        "Sidi Naamane",
        "Souamaa",
        "Souk El Thenine",
        "Tadmait",
        "Tigzirt",
        "Timizart",
        "Tirmitine",
        "Tizi Ghenif",
        "Tizi N'tleta",
        "Tizi Ouzou",
        "Tizi Rached",
        "Yakourene",
        "Yatafene",
        "Zekri"
      ]
  ),
  wilaya(13,'Tlemcen','Tlemcen',i1: 800, i2: 450,['Tlemcen'],
      {
            'Tlemcen': 'N 351 HAI LES DALIAS EL KIFFANE',
      },
      [
        "Ain Fettah",
        "Ain Fezza",
        "Ain Ghoraba",
        "Ain Kebira",
        "Ain Nehala",
        "Ain Tallout",
        "Ain Youcef",
        "Amieur",
        "Azails",
        "Bab El Assa",
        "Beni Bahdel",
        "Beni Boussaid",
        "Beni Khaled",
        "Beni Mester",
        "Beni Ouarsous",
        "Beni Smiel",
        "Beni Snous",
        "Bensekrane",
        "Bouhlou",
        "Bouihi",
        "Chetouane",
        "Dar Yaghmouracene",
        "Djebala",
        "El Aricha",
        "El Fehoul",
        "El Gor",
        "Fellaoucene",
        "Ghazaouet",
        "Hammam Boughrara",
        "Hennaya",
        "Honaine",
        "Maghnia",
        "Mansourah",
        "Marsa Ben M'hidi",
        "Msirda Fouaga",
        "Nedroma",
        "Oued Chouly",
        "Ouled Mimoun",
        "Ouled Riyah",
        "Remchi",
        "Sabra",
        "Sebbaa Chioukh",
        "Sebdou",
        "Sidi Abdelli",
        "Sidi Djilali",
        "Sidi Medjahed",
        "Souahlia",
        "Souani",
        "Souk Tleta",
        "Terny Beni Hediel",
        "Tianet",
        "Tlemcen",
        "Zenata"
      ]
  ),
  wilaya(34,'Bordj Bou Arreridj','Bordj Bou Arreridj',i1: 700, i2: 450,['Bordj Bou Arreridj'],
      {
            'Bordj Bou Arreridj': 'City 1008 proche de librairie amir',
      },
      [
        "Ain Taghrout",
        "Ain Tesra",
        "Belimour",
        "Ben Daoud",
        "Bir Kasdali",
        "Bordj Bou Arreridj",
        "Bordj Ghdir",
        "Bordj Zemora",
        "Colla",
        "Djaafra",
        "El Ach",
        "El Achir",
        "El Anseur",
        "El Hamadia",
        "El M'hir",
        "El Main",
        "Ghilassa",
        "Haraza",
        "Hasnaoua",
        "Khelil",
        "Ksour",
        "Mansoura",
        "Medjana",
        "Ouled Brahem",
        "Ouled Dahmane",
        "Ouled Sidi Brahim",
        "Rabta",
        "Ras El Oued",
        "Sidi Embarek",
        "Tafreg",
        "Taglait",
        "Teniet En Nasr",
        "Tesmart",
        "Tixter"
      ]
  ),
  wilaya(19,'Sétif','Setif',i1: 750, i2: 450,['El Eulma','Setif'],
      {
            'El Eulma': 'Eulma tashomi',
            'Setif': 'City batwar a côté de Marché automobile hebdomadaire',
      },
      [
        "Ain Abessa",
        "Ain Arnat",
        "Ain Azel",
        "Ain El Kebira",
        "Ain Lahdjar",
        "Ain Legradj",
        "Ain Oulmane",
        "Ain Roua",
        "Ain Sebt",
        "Ait Naoual Mezada",
        "Ait Tizi",
        "Amoucha",
        "Babor",
        "Bazer Sakra",
        "Beidha Bordj",
        "Bellaa",
        "Beni Aziz",
        "Beni Chebana",
        "Beni Fouda",
        "Beni Mouhli",
        "Beni Ouartilane",
        "Beni Oussine",
        "Bir El Arch",
        "Bir Haddada",
        "Bouandas",
        "Bougaa",
        "Bousselam",
        "Boutaleb",
        "Dehamcha",
        "Djemila",
        "Draa Kebila",
        "El Eulma",
        "El Ouldja",
        "El Ouricia",
        "Guellal",
        "Guelta Zerka",
        "Guenzet",
        "Guidjel",
        "Hamam Soukhna",
        "Hamma",
        "Hammam Guergour",
        "Harbil",
        "Ksar El Abtal",
        "Maaouia",
        "Maouaklane",
        "Mezloug",
        "Oued El Barad",
        "Ouled Addouane",
        "Ouled Sabor",
        "Ouled Si Ahmed",
        "Ouled Tebben",
        "Rosfa",
        "Salah Bey",
        "Serdj El Ghoul",
        "Setif",
        "Tachouda",
        "Tala Ifacene",
        "Taya",
        "Tella",
        "Tizi N'bechar"
      ]
  ),
  wilaya(18,'Jijel','Jijel',i1: 750, i2: 450,['Djemaa Beni Habibi','Jijel'],
      {
            'Djemaa Beni Habibi': 'RUE GHARBI SALAH',
            'Jijel': 'Rue chrikan Ali',
      },
      [
        "Bordj Tahar",
        "Boudria Beniyadjis",
        "Bouraoui Belhadef",
        "Boussif Ouled Askeur",
        "Chahna",
        "Chekfa",
        "Djemaa Beni Habibi",
        "Djimla",
        "El Ancer",
        "El Aouana",
        "El Kennar Nouchfi",
        "El Milia",
        "Emir Abdelkader",
        "Erraguene",
        "Ghebala",
        "Jijel",
        "Khiri Oued Adjoul",
        "Kouas",
        "Oudjana",
        "Ouled Rabah",
        "Ouled Yahia Khadrouch",
        "Selma Benziada",
        "Settara",
        "Sidi Abdelaziz",
        "Sidi Marouf",
        "Taher",
        "Texena",
        "Ziama Mansouria"
      ]
  ),
  wilaya(43,'Mila','Mila',i1: 750, i2: 450,['Mila'],
      {
            'Mila': "En face l'office national d'assainissement (ONA)",
      },
      [
            "Ahmed Rachedi",
            "Ain Beida Harriche",
            "Ain Mellouk",
            "Ain Tine",
            "Amira Arres",
            "Benyahia Abderrahmane",
            "Bouhatem",
            "Chelghoum Laid",
            "Chigara",
            "Derrahi Bousselah",
            "El Mechira",
            "Elayadi Barbes",
            "Ferdjioua",
            "Grarem Gouga",
            "Hamala",
            "Mila",
            "Minar Zarza",
            "Oued Athmenia",
            "Oued Endja",
            "Oued Seguen",
            "Ouled Khalouf",
            "Rouached",
            "Sidi Khelifa",
            "Sidi Merouane",
            "Tadjenanet",
            "Tassadane Haddada",
            "Teleghma",
            "Terrai Bainem",
            "Tessala",
            "Tiberguent",
            "Yahia Beniguecha",
            "Zeghaia"
      ]  ),
  wilaya(25,'Constantine','',i1: 750, i2: 450,['El Khroub'],
      {
            'El Khroub': 'Cite mànar en face SNTV',
      },
      [
        "Ain Abid",
        "Ain Smara",
        "Ben Badis",
        "Beni Hamidene",
        "Constantine",
        "Didouche Mourad",
        "El Khroub",
        "Hamma Bouziane",
        "Ibn Ziad",
        "Messaoud Boujeriou",
        "Ouled Rahmouni",
        "Zighoud Youcef"
      ]
  ),
  wilaya(21,'Skikda','Skikda',i1: 750, i2: 450,['Skikda'],
      {
            'Skikda': 'A coté de El NASR Mosque',
      },
      [
        "Ain Bouziane",
        "Ain Charchar",
        "Ain Kechera",
        "Ain Zouit",
        "Azzaba",
        "Bekkouche Lakhdar",
        "Ben Azzouz",
        "Beni Bechir",
        "Beni Oulbane",
        "Beni Zid",
        "Bin El Ouiden",
        "Bouchetata",
        "Cheraia",
        "Collo",
        "Djendel Saadi Mohamed",
        "El Arrouch",
        "El Ghedir",
        "El Hadaiek",
        "El Marsa",
        "Emjez Edchich",
        "Es Sebt",
        "Filfila",
        "Hamadi Krouma",
        "Kanoua",
        "Kerkera",
        "Khenag Mayoum",
        "Oued Zhour",
        "Ouldja Boulbalout",
        "Ouled Attia",
        "Ouled Habbeba",
        "Oum Toub",
        "Ramdane Djamel",
        "Salah Bouchaour",
        "Sidi Mezghiche",
        "Skikda",
        "Tamalous",
        "Zerdezas",
        "Zitouna"
      ]
  ),
  wilaya(20,'Saïda','Saida',i1: 800, i2: 500,['Saida'],
      {
            'Saida': 'Saide centre ville, deriere cinema El Fath',
      },
      [
        "Ain El Hadjar",
        "Ain Sekhouna",
        "Ain Soltane",
        "Doui Thabet",
        "El Hassasna",
        "Hounet",
        "Maamora",
        "Moulay Larbi",
        "Ouled Brahim",
        "Ouled Khaled",
        "Saida",
        "Sidi Ahmed",
        "Sidi Amar",
        "Sidi Boubekeur",
        "Tircine",
        "Youb"
      ]
  ),
  wilaya(40,'Khenchela','Khenchela',i1: 800, i2: 500,['Khenchela'],
      {
            'Khenchela': 'Rue 1er Novembre, près de Sonelgaz et du Jardin du 1er Novembre',
      },
      [
        "Ain Touila",
        "Babar",
        "Baghai",
        "Bouhmama",
        "Chelia",
        "Cherchar",
        "Djellal",
        "El Hamma",
        "El Mahmal",
        "El Oueldja",
        "Ensigha",
        "Kais",
        "Khenchela",
        "Khirane",
        "M'sara",
        "M'toussa",
        "Ouled Rechache",
        "Remila",
        "Tamza",
        "Taouzianat",
        "Yabous"
      ]
  ),
  wilaya(23,'Annaba','Annaba',i1: 750, i2: 450,['Annaba'],
      {
            'Annaba': 'Cite oued edheb 2 bâtiment C2 en face CASNOS',
      },
      [
        "Ain Berda",
        "Annaba",
        "Berrahel",
        "Chetaibi",
        "Cheurfa",
        "El Bouni",
        "El Hadjar",
        "Eulma",
        "Oued El Aneb",
        "Seraidi",
        "Sidi Amar",
        "Treat"
      ]
  ),
  wilaya(41,'Souk Ahras','Souk Ahras',i1: 800, i2: 500,['Souk Ahras'],
      {
            'Souk Ahras': 'Nahdj Slimane Amirat',
      },
      [
        "Ain Soltane",
        "Ain Zana",
        "Bir Bouhouche",
        "Drea",
        "Haddada",
        "Hanencha",
        "Khedara",
        "Khemissa",
        "M'daourouche",
        "Machroha",
        "Merahna",
        "Oued Kebrit",
        "Ouled Driss",
        "Ouled Moumen",
        "Oum El Adhaim",
        "Quillen",
        "Ragouba",
        "Safel El Ouiden",
        "Sedrata",
        "Sidi Fredj",
        "Souk Ahras",
        "Taoura",
        "Terraguelt",
        "Tiffech",
        "Zaarouria",
        "Zouabi"
      ]
  ),
  wilaya(24,'Guelma','Guelma',i1: 750, i2: 450,['Guelma'],
      {
            'Guelma': 'Fardas Hussein n°06, Magasin n°01',
      },
      [
        "Ain Ben Beida",
        "Ain Hessania",
        "Ain Larbi",
        "Ain Makhlouf",
        "Ain Reggada",
        "Belkheir",
        "Ben Djarah",
        "Beni Mezline",
        "Bordj Sabat",
        "Bou Hachana",
        "Bou Hamdane",
        "Bouati Mahmoud",
        "Bouchegouf",
        "Bouhamra Ahmed",
        "Dahouara",
        "Djeballah Khemissi",
        "El Fedjoudj",
        "Guelaat Bou Sbaa",
        "Guelma",
        "Hamam Debagh",
        "Hammam N'bail",
        "Heliopolis",
        "Khezara",
        "Medjez Amar",
        "Medjez Sfa",
        "Nechmaya",
        "Oued Cheham",
        "Oued Fragha",
        "Oued Zenati",
        "Ras El Agba",
        "Roknia",
        "Sellaoua Announa",
        "Sidi Sandel",
        "Tamlouka"
      ]
  ),
  wilaya(17,'Djelfa','Djelfa',i1: 850, i2: 550,['Djelfa'],
      {
            'Djelfa': 'Quartier Ben Tayba, rue Boukhalifa, près de la station-service',
      },
      [
        "Ain Chouhada",
        "Ain El Ibel",
        "Ain Fekka",
        "Ain Maabed",
        "Ain Oussera",
        "Amourah",
        "Benhar",
        "Benyagoub",
        "Birine",
        "Bouira Lahdab",
        "Charef",
        "Dar Chioukh",
        "Deldoul",
        "Djelfa",
        "Douis",
        "El Guedid",
        "El Idrissia",
        "El Khemis",
        "Faidh El Botma",
        "Guernini",
        "Guettara",
        "Had Sahary",
        "Hassi Bahbah",
        "Hassi El Euch",
        "Hassi Fedoul",
        "M Liliha",
        "Messaad",
        "Moudjebara",
        "Oum Laadham",
        "Sed Rahal",
        "Selmana",
        "Sidi Baizid",
        "Sidi Ladjel",
        "Tadmit",
        "Zaafrane",
        "Zaccar"
      ]
  ),
  wilaya(46,'Aïn Témouchent','Ain Temouchent',i1: 750, i2: 450,['Ain Temouchent'],
      s0: 'MED',
      {
            'Ain Temouchent': 'Cité El Zitoun',
      },
      [
            "Aghlal",
            "Ain El Arbaa",
            "Ain Kihal",
            "Ain Temouchent",
            "Ain Tolba",
            "Aoubellil",
            "Beni Saf",
            "Bouzedjar",
            "Chaabat El Ham",
            "Chentouf",
            "El Amria",
            "El Malah",
            "El Messaid",
            "Emir Abdelkader",
            "Hammam Bouhadjar",
            "Hassasna",
            "Hassi El Ghella",
            "Oued Berkeche",
            "Oued Sebbah",
            "Ouled Boudjemaa",
            "Ouled Kihal",
            "Oulhaca El Gheraba",
            "Sidi Ben Adda",
            "Sidi Boumediene",
            "Sidi Ouriache",
            "Sidi Safi",
            "Tamzoura",
            "Terga"
      ]  ),
  wilaya(7,'Biskra','Biskra',i1: 900, i2: 550,['Biskra'],s0: 'MED',
      {
            'Biskra': 'Cité Zarzour, Côté droit',
      },
      [
            "Ain Naga",
            "Ain Zaatout",
            "Biskra",
            "Bordj Ben Azzouz",
            "Bouchagroun",
            "Branis",
            "Chetma",
            "Djemorah",
            "El Feidh",
            "El Ghrous",
            "El Hadjab",
            "El Haouch",
            "El Kantara",
            "El Outaya",
            "Foughala",
            "Khenguet Sidi Nadji",
            "Lichana",
            "Lioua",
            "M'chouneche",
            "M'lili",
            "Mekhadma",
            "Meziraa",
            "Oumache",
            "Ourlal",
            "Sidi Okba",
            "Tolga",
            "Zeribet El Oued"
      ]  ),
  wilaya(32,'El Bayadh','El Bayadh',i1: 1000, i2: 650,['El Bayadh'],
      {
            'El Bayadh': "A coté de l'Hotel Benkayoum",
      },
      [
        "Ain El Orak",
        "Arbaouat",
        "Boualem",
        "Bougtoub",
        "Boussemghoun",
        "Brezina",
        "Cheguig",
        "Chellala",
        "El Bayadh",
        "El Biodh Sidi Cheikh",
        "El Bnoud",
        "El Kheither",
        "El Mehara",
        "Ghassoul",
        "Kef El Ahmar",
        "Krakda",
        "Rogassa",
        "Sidi Ameur",
        "Sidi Slimane",
        "Sidi Tifour",
        "Stitten",
        "Tousmouline"
      ]
  ),
  wilaya(12,'Tébessa','Tebessa',i1: 850, i2: 550,['Tebessa'],
      {
            'Tebessa': 'Skanska, derrière la mosquée Cheikh Larbi Tébessi',
      },
      [
            "Ain Zerga",
            "Bedjene",
            "Bekkaria",
            "Bir Dheheb",
            "Bir El Ater",
            "Bir Mokkadem",
            "Boukhadra",
            "Boulhaf Dyr",
            "Cheria",
            "El Aouinet",
            "El Houidjbet",
            "El Kouif",
            "El Malabiod",
            "El Meridj",
            "El Mezeraa",
            "El Ogla",
            "El Ogla El Malha",
            "Ferkane",
            "Guorriguer",
            "Hammamet",
            "Morssot",
            "Negrine",
            "Ouenza",
            "Oum Ali",
            "Saf Saf El Ouesra",
            "Stah Guentis",
            "Tebessa",
            "Telidjen"
      ]
        ),
  wilaya(3,'Laghouat','Laghouat',i1: 900, i2: 600,['Laghouat'],
      {
            'Laghouat': "Cite mkam route nationale n' 1on fasse café mon ami",
      },
      [
        "Aflou",
        "Ain Madhi",
        "Ain Sidi Ali",
        "Beidha",
        "Benacer Benchohra",
        "Brida",
        "El Assafia",
        "El Ghicha",
        "El Haouaita",
        "Gueltat Sidi Saad",
        "Hadj Mechri",
        "Hassi Delaa",
        "Hassi R'mel",
        "Kheneg",
        "Ksar El Hirane",
        "Laghouat",
        "Oued M'zi",
        "Oued Morra",
        "Sebgag",
        "Sidi Bouzid",
        "Sidi Makhlouf",
        "Tadjemout",
        "Tadjrouna",
        "Taouiala"
      ]
  ),
  wilaya(39,'El Oued','El Oued',i1: 1000, i2: 650,['El Oued'],s0: 'MED',
      {
            'El Oued': 'Cité El Rimal 2, Route du Centre Financier',
      },
      [
            "Bayadha",
            "Ben Guecha",
            "Debila",
            "Douar El Maa",
            "El Ogla",
            "El Oued",
            "Guemar",
            "Hamraia",
            "Hassani Abdelkrim",
            "Hassi Khalifa",
            "Kouinine",
            "Magrane",
            "Mih Ouansa",
            "Nakhla",
            "Oued El Alenda",
            "Ourmes",
            "Reguiba",
            "Robbah",
            "Sidi Aoun",
            "Taghzout",
            "Taleb Larbi",
            "Trifaoui"
      ]
  ),
  wilaya(30,'Ouargla','Ouargla',i1: 1000, i2: 650,['Ouargla'],s0: 'MED',
      {
            'Ouargla': 'Cité El Chérifa',
      },
      [
            "Ain Beida",
            "El Borma",
            "Hassi Ben Abdellah",
            "Hassi Messaoud",
            "N'goussa",
            "Ouargla",
            "Rouissat",
            "Sidi Khouiled"
      ]  ),
  wilaya(57,"El M'Ghair","El M'ghair",i1: 950, i2: 650,["El M'ghair"],s0: 'MED',
      {
            "El M'ghair": "Cité 360 Logements, en face de l'Agence de Voyages Ben Ali",
      },
      [
            "Djamaa",
            "El M'ghair",
            "Mrara",
            "Oum Touyour",
            "Sidi Amrane",
            "Sidi Khelil",
            "Still",
            "Tenedla"
      ]  ),
  wilaya(44,'Aïn Defla','Ain Defla',i1: 650, i2: 400,['Ain Defla'],
      {
            'Ain Defla': 'Cartier kadour Al arbie',
      },
      [
        "Ain Benian",
        "Ain Bouyahia",
        "Ain Defla",
        "Ain Lechiakh",
        "Ain Soltane",
        "Ain Tork",
        "Arib",
        "Barbouche",
        "Bathia",
        "Belaas",
        "Ben Allal",
        "Bir Ould Khelifa",
        "Bordj Emir Khaled",
        "Boumedfaa",
        "Bourached",
        "Djelida",
        "Djemaa Ouled Cheikh",
        "Djendel",
        "El Abadia",
        "El Amra",
        "El Attaf",
        "El Maine",
        "Hammam Righa",
        "Hassania",
        "Hoceinia",
        "Khemis Miliana",
        "Mekhatria",
        "Miliana",
        "Oued Chorfa",
        "Oued Djemaa",
        "Rouina",
        "Sidi Lakhdar",
        "Tacheta Zegagha",
        "Tarik Ibn Ziad",
        "Tiberkanine",
        "Zeddine"
      ]
  ),
  wilaya(35,'Boumerdès','Boumerdes',i1: 700, i2: 450,['Boumerdes'],
      {
            'Boumerdes': 'La coopérative immobilier Alwafaa bâtiment 49',
      },
      [
        "Afir",
        "Ammal",
        "Baghlia",
        "Ben Choud",
        "Beni Amrane",
        "Bordj Menaiel",
        "Boudouaou",
        "Boudouaou El Bahri",
        "Boumerdes",
        "Bouzegza Keddara",
        "Chabet El Ameur",
        "Corso",
        "Dellys",
        "Djinet",
        "El Kharrouba",
        "Hammedi",
        "Isser",
        "Khemis El Khechna",
        "Larbatache",
        "Leghata",
        "Naciria",
        "Ouled Aissa",
        "Ouled Hedadj",
        "Ouled Moussa",
        "Si Mustapha",
        "Sidi Daoud",
        "Souk El Haad",
        "Taourga",
        "Thenia",
        "Tidjelabine",
        "Timezrit",
        "Zemmouri"
      ]
  ),
  wilaya(48,'Relizane','Relizane',i1: 700, i2: 400,['Relizane'],
      {
            'Relizane': 'Cité zitoun a côté de cnas',
      },
      [
        "Ain Rahma",
        "Ain Tarek",
        "Ammi Moussa",
        "Belaassel Bouzagza",
        "Bendaoud",
        "Beni Dergoun",
        "Beni Zentis",
        "Dar Ben Abdelah",
        "Djidiouia",
        "El Guettar",
        "El H'madna",
        "El Hassi",
        "El Matmar",
        "El Ouldja",
        "Had Echkalla",
        "Hamri",
        "Kalaa",
        "Lahlef",
        "Mazouna",
        "Mediouna",
        "Mendes",
        "Merdja Sidi Abed",
        "Ouarizane",
        "Oued El Djemaa",
        "Oued Essalem",
        "Oued Rhiou",
        "Ouled Aiche",
        "Ouled Sidi Mihoub",
        "Ramka",
        "Relizane",
        "Sidi Khettab",
        "Sidi Lazreg",
        "Sidi M'hamed Benali",
        "Sidi M'hamed Benaouda",
        "Sidi Saada",
        "Souk El Had",
        "Yellel",
        "Zemmoura"
      ]
  ),
  wilaya(10,'Bouira','Bouira',i1: 700, i2: 450,['Bouira','Sour El Ghozlane'],
      {
            'Bouira': 'Rue amar khodja 72',
            'Sour El Ghozlane': 'Bouchlaghem',
      },
      [
        "Aghbalou",
        "Ahl El Ksar",
        "Ain Bessem",
        "Ain El Hadjar",
        "Ain Laloui",
        "Ain Turk",
        "Ait Laaziz",
        "Aomar",
        "Bechloul",
        "Bir Ghbalou",
        "Bordj Okhriss",
        "Bouderbala",
        "Bouira",
        "Boukram",
        "Chorfa",
        "Dechmia",
        "Dirah",
        "Djebahia",
        "El Adjiba",
        "El Asnam",
        "El Hachimia",
        "El Hakimia",
        "El Khabouzia",
        "El Mokrani",
        "Guerrouma",
        "Hadjera Zerga",
        "Haizer",
        "Hanif",
        "Kadiria",
        "Lakhdaria",
        "M Chedallah",
        "Maala",
        "Mamora",
        "Mezdour",
        "Oued El Berdi",
        "Ouled Rached",
        "Raouraoua",
        "Ridane",
        "Saharidj",
        "Souk El Khemis",
        "Sour El Ghozlane",
        "Taghzout",
        "Taguedite",
        "Taourirt",
        "Z'barbar"
      ]
  ),
  wilaya(6,'Béjaïa','Bejaia',i1: 750, i2: 450,['Akbou','Bejaia','Kherrata'],
      {
            'Akbou': 'À côté de Stade Scolaire',
            'Bejaia': 'Cité kherroubi derrière la gare routière',
            'Kherrata': 'Fin du pont Laouadher, à côté du cabinet Mansouri',
      },
      [
        "Adekar",
        "Ait R'zine",
        "Ait Smail",
        "Akbou",
        "Akfadou",
        "Amalou",
        "Amizour",
        "Aokas",
        "Barbacha",
        "Bejaia",
        "Beni Dejllil",
        "Beni K'sila",
        "Beni Mallikeche",
        "Benimaouche",
        "Boudjellil",
        "Bouhamza",
        "Boukhelifa",
        "Chellata",
        "Chemini",
        "Darghina",
        "Dra El Caid",
        "El Kseur",
        "Fenaia Il Maten",
        "Feraoun",
        "Ighil Ali",
        "Ighram",
        "Kendira",
        "Kherrata",
        "Leflaye",
        "M'cisna",
        "Melbou",
        "Oued Ghir",
        "Ouzellaguene",
        "Seddouk",
        "Sidi Aich",
        "Sidi Ayad",
        "Smaoun",
        "Souk El Tenine",
        "Souk Oufella",
        "Tala Hamza",
        "Tamokra",
        "Tamridjet",
        "Taourit Ighil",
        "Taskriout",
        "Tazmalt",
        "Tibane",
        "Tichy",
        "Tifra",
        "Timezrit",
        "Tinebdar",
        "Tizi N'berber",
        "Toudja"
      ]
  ),
  wilaya(38,'Tissemsilt','Tissemsilt',i1: 800, i2: 500,['Tissemsilt'],
      {
            'Tissemsilt': 'En face rond point ben lachehab',
      },
      [
        "Ammari",
        "Beni Chaib",
        "Beni Lahcene",
        "Bordj Bounaama",
        "Bordj El Emir Abdelkader",
        "Bou Caid",
        "Khemisti",
        "Larbaa",
        "Lardjem",
        "Layoune",
        "Lazharia",
        "Maacem",
        "Melaab",
        "Ouled Bessem",
        "Sidi Abed",
        "Sidi Boutouchent",
        "Sidi Lantri",
        "Sidi Slimane",
        "Tamellalet",
        "Theniet El Had",
        "Tissemsilt",
        "Youssoufia"
      ]
  ),
  wilaya(28,"M'Sila","M'sila",i1: 800, i2: 500,["Berhoum","M'sila"],
      {
            'Berhoum': 'A coté de CEM Flak Allaoua',
            "M'sila": 'Quartier 500 logements, en face du lycée Zaghba Draji',
      },
      [
        "Ain El Hadjel",
        "Ain El Melh",
        "Ain Fares",
        "Ain Khadra",
        "Ain Rich",
        "Belaiba",
        "Ben Srour",
        "Beni Ilmane",
        "Benzouh",
        "Berhoum",
        "Bir Foda",
        "Bou Saada",
        "Bouti Sayeh",
        "Chellal",
        "Dehahna",
        "Djebel Messaad",
        "El Hamel",
        "El Houamed",
        "Hammam Dalaa",
        "Khettouti Sed El Jir",
        "Khoubana",
        "M'cif",
        "M'sila",
        "M'tarfa",
        "Maadid",
        "Maarif",
        "Magra",
        "Medjedel",
        "Menaa",
        "Mohamed Boudiaf",
        "Ouanougha",
        "Ouled Addi Guebala",
        "Ouled Derradj",
        "Ouled Madhi",
        "Ouled Mansour",
        "Ouled Sidi Brahim",
        "Ouled Slimane",
        "Oulteme",
        "Sidi Aissa",
        "Sidi Ameur",
        "Sidi Hadjeres",
        "Sidi M'hamed",
        "Slim",
        "Souamaa",
        "Tamsa",
        "Tarmount",
        "Zarzour"
      ]
  ),
  wilaya(29,'Mascara','Mascara',i1: 800, i2: 500,['Mascara'],
      {
            'Mascara': 'Rue bouremla habib',
      },
      [
        "Ain Fares",
        "Ain Fekan",
        "Ain Ferah",
        "Ain Frass",
        "Alaimia",
        "Aouf",
        "Benian",
        "Bou Henni",
        "Bouhanifia",
        "Chorfa",
        "El Bordj",
        "El Gaada",
        "El Ghomri",
        "El Gueitena",
        "El Hachem",
        "El Keurt",
        "El Mamounia",
        "El Menaouer",
        "Ferraguig",
        "Froha",
        "Gharrous",
        "Ghriss",
        "Guerdjoum",
        "Hacine",
        "Khalouia",
        "Makhda",
        "Maoussa",
        "Mascara",
        "Matemore",
        "Mocta Douz",
        "Mohammadia",
        "Nesmot",
        "Oggaz",
        "Oued El Abtal",
        "Oued Taria",
        "Ras El Ain Amirouche",
        "Sedjerara",
        "Sehailia",
        "Sidi Abdeldjebar",
        "Sidi Abdelmoumene",
        "Sidi Boussaid",
        "Sidi Kada",
        "Sig",
        "Tighennif",
        "Tizi",
        "Zahana",
        "Zelamta"
      ]
  ),
  wilaya(5,'Batna','Batna',i1: 800, i2: 450,['Batna'],
      {
            'Batna': 'À côté de la grande porte de l’Université Hadj Lakhdar',
      },
      [
        "Ain Djasser",
        "Ain Touta",
        "Ain Yagout",
        "Arris",
        "Azil Abedelkader",
        "Barika",
        "Batna",
        "Beni Foudhala El Hakania",
        "Bitam",
        "Boulhilat",
        "Boumagueur",
        "Boumia",
        "Bouzina",
        "Chemora",
        "Chir",
        "Djerma",
        "Djezzar",
        "El Hassi",
        "El Madher",
        "Fesdis",
        "Foum Toub",
        "Ghassira",
        "Gosbat",
        "Guigba",
        "Hidoussa",
        "Ichmoul",
        "Inoughissen",
        "Kimmel",
        "Ksar Bellezma",
        "Larbaa",
        "Lazrou",
        "Lemsane",
        "M Doukal",
        "Maafa",
        "Menaa",
        "Merouana",
        "N Gaous",
        "Oued Chaaba",
        "Oued El Ma",
        "Oued Taga",
        "Ouled Ammar",
        "Ouled Aouf",
        "Ouled Fadel",
        "Ouled Sellem",
        "Ouled Si Slimane",
        "Ouyoun El Assafir",
        "Rahbat",
        "Ras El Aioun",
        "Sefiane",
        "Seggana",
        "Seriana",
        "T Kout",
        "Talkhamt",
        "Taxlent",
        "Tazoult",
        "Teniet El Abed",
        "Tighanimine",
        "Tigharghar",
        "Tilatou",
        "Timgad",
        "Zanet El Beida"
      ]
  ),
  wilaya(36,'El Tarf','El Tarf',i1: 850, i2: 550,['El Tarf'],
      {
            'El Tarf': 'Quartier riche à côté de notaire Achouri',
      },
      [
        "Ain El Assel",
        "Ain Kerma",
        "Asfour",
        "Ben M Hidi",
        "Berrihane",
        "Besbes",
        "Bougous",
        "Bouhadjar",
        "Bouteldja",
        "Chebaita Mokhtar",
        "Chefia",
        "Chihani",
        "Drean",
        "Echatt",
        "El Aioun",
        "El Kala",
        "El Tarf",
        "Hammam Beni Salah",
        "Lac Des Oiseaux",
        "Oued Zitoun",
        "Raml Souk",
        "Souarekh",
        "Zerizer",
        "Zitouna"
      ]
  ),
  wilaya(55,'Touggourt','Touggourt',i1: 1000, i2: 650,['Touggourt'],
      {
            'Touggourt': "En face de L'APC",
      },
      [
        "Benaceur",
        "Blidet Amor",
        "El Alia",
        "El Hadjira",
        "Megarine",
        "Mnaguer",
        "Nezla",
        "Sidi Slimane",
        "Taibet",
        "Tebesbest",
        "Temacine",
        "Touggourt",
        "Zaouia El Abidia"
      ]
  ),
  wilaya(45,'Naâma','Naama',i1: 1000, i2: 650,['Mecheria'],
      {
            'Mecheria': 'Rue ben chikh mohammed centre ville',
      },
      [
        "Ain Ben Khelil",
        "Ain Safra",
        "Assela",
        "Djeniane Bourzeg",
        "El Biod",
        "Kasdir",
        "Makman Ben Amer",
        "Mecheria",
        "Moghrar",
        "Naama",
        "Sfissifa",
        "Tiout"
      ]
  ),
  wilaya(8,'Béchar','Bechar',i1: 1200, i2: 800,['Bechar'],
      {
            'Bechar': 'A coté de la Bibliothèque centrale',
      },
      [
        "Abadla",
        "Bechar",
        "Beni Ounif",
        "Boukais",
        "Erg Ferradj",
        "Kenadsa",
        "Lahmar",
        "Mechraa H.boumediene",
        "Meridja",
        "Mogheul",
        "Taghit"
      ]
  ),
];